# Generated by Django 5.1.1 on 2024-11-10 09:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineStatusTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_one_checkout', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_two_checkout', models.DateTimeField(default=django.utils.timezone.now)),
                ('userOne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_as_user_one', to=settings.AUTH_USER_MODEL)),
                ('userTwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_as_user_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('userOne', 'userTwo')},
            },
        ),
    ]
